#!/usr/bin/env bash
# ransomware.sh - จำลองพฤติกรรม ransomware
# เลข test ยืนยันจาก check_atomics.sh บนเครื่องจริง
#
# ATT&CK:
#   T1083     3,4,8    File and Directory Discovery
#   T1074.001 2        Local Data Staging
#   T1486     1,2,3,4  Data Encrypted for Impact (gpg/7z/ccrypt/openssl)
#   T1070.004 1,2,3    Indicator Removal - File Deletion
#   T1490              ไม่มี Linux test -> ตัดออก
#
# ⚠️ ห้ามใส่ T1070.004 test 8 (Delete Filesystem) จะล้างเครื่องทั้งลูก
set -uo pipefail
source "$(dirname "$0")/_lib.sh"
banner "ransomware"
setup_sandbox

VICTIM="$SANDBOX/victim_files"
mkdir -p "$VICTIM"

echo "[ransom] สร้างไฟล์เหยื่อจำลอง 60 ไฟล์"
for i in $(seq 1 60); do
    head -c 4096 /dev/urandom | base64 > "$VICTIM/document_$i.txt"
done

# --- Stage 1: สำรวจไฟล์เป้าหมาย ---
atomic T1083 3,4,8

# --- Stage 2: รวบรวมไฟล์ไว้ที่เดียว ---
atomic T1074.001 2

# --- Stage 3: เข้ารหัส 4 วิธี (ProcessCreate หลากหลาย) ---
atomic T1486 1,2,3,4

# --- Stage 4: เข้ารหัสเองใน sandbox (FileCreate + FileDelete หนาแน่น) ---
echo "[ransom] เข้ารหัสไฟล์ใน sandbox"
KEY="labkey$(date +%s)"
for f in "$VICTIM"/*.txt; do
    openssl enc -aes-256-cbc -pbkdf2 -salt -in "$f" -out "$f.locked" -pass pass:"$KEY" 2>/dev/null
    rm -f "$f"
done

cat > "$VICTIM/READ_ME_RECOVERY.txt" <<'NOTE'
[LAB SIMULATION ONLY - NOT REAL RANSOMWARE]
Generated by a thesis experiment. No actual harm.
NOTE

# --- Stage 5: ลบร่องรอย (เฉพาะ 1,2,3 ห้าม 8) ---
atomic T1070.004 1,2,3

echo "[ransom] ลบไฟล์จำนวนมาก"
for i in $(seq 1 30); do echo "temp$i" > "$SANDBOX/tmp_$i.dat"; done
rm -f "$SANDBOX"/tmp_*.dat

done_banner "ransomware"