# ransomware_win.ps1 - ransomware behaviour (Windows) ผ่าน Atomic Red Team
# แทนที่ ransomware_real_win.ps1 (เวอร์ชันเขียน AES เอง)
#
# การเข้ารหัสทำโดย atomic test T1486 ทั้งหมด - ไม่มี crypto routine เขียนเองในไฟล์นี้
# ส่วนกิจกรรมไฟล์ (สร้าง/ลบจำนวนมาก) เป็น operation ปกติของ Windows
# ใช้เพื่อให้ได้ FileCreate(11)/FileDelete(23) telemetry หนาแน่นเหมือน ransomware จริง
#
# ATT&CK: T1083 File Discovery, T1074.001 Local Staging, T1005 Collection,
#         T1486 Data Encrypted for Impact, T1070.004 File Deletion
#
# ⚠️ ต้องรัน PowerShell แบบ Administrator
# ⚠️ ระบุเลข test เสมอ - Atomic() ที่ไม่ระบุจะรันทุก test ของ technique นั้น
. "$PSScriptRoot\_lib.ps1"
Banner "ransomware_win"
Setup-Sandbox

$victim = "C:\lab_sandbox\victim_files"
New-Item -ItemType Directory -Path $victim -Force | Out-Null

$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[!] ไม่ได้รันแบบ Administrator - test บางตัวจะ fail" -ForegroundColor Yellow
}

# ---------- Stage 1: สร้างไฟล์เป้าหมายใน sandbox ----------
# ไฟล์ล่อสำหรับให้ atomic test ทำงาน + สร้าง FileCreate telemetry
Write-Host "[ransom] สร้างไฟล์เป้าหมาย"
$exts = @("docx","xlsx","pdf","jpg","txt","csv","pptx","sql","zip","png")
1..60 | ForEach-Object {
    $ext  = $exts[$_ % $exts.Count]
    $f    = Join-Path $victim ("document_{0:D3}.{1}" -f $_, $ext)
    $size = Get-Random -Minimum 2048 -Maximum 20480
    $buf  = New-Object byte[] $size
    (New-Object Random).NextBytes($buf)
    [System.IO.File]::WriteAllBytes($f, $buf)
}
Write-Host "[ransom] victim files = $((Get-ChildItem $victim -File).Count)"

# ---------- Stage 2: สำรวจไฟล์เป้าหมาย ----------
Write-Host "[ransom] discovery"
Atomic "T1083" "1,2,5,6,7,9"             # File and Directory Discovery
Atomic "T1005" "1"               # Data from Local System

# ---------- Stage 3: staging ----------
Write-Host "[ransom] staging"
Atomic "T1074.001" "1,3"           # Local Data Staging

# ---------- Stage 4: เข้ารหัส (ART จัดการทั้งหมด) ----------
Write-Host "[ransom] encryption via ART"
Atomic "T1486" "5,8,10"          # Data Encrypted for Impact
# หมายเหตุ: T1486 บน Windows มี 4 test (5,8,9,10)
#   ตัด test 9 (DiskCryptor) ออกเอง - มันติดตั้ง driver เข้ารหัสทั้ง volume
#   checker ไม่ได้จับตัวนี้เพราะ command ไม่มี keyword ที่สแกน
#   test 8 (GPG4Win) ต้องโหลด+ติดตั้งผ่านเน็ต ใช้เวลาราว 1-2 นาที

# ---------- Stage 5: กิจกรรมไฟล์หนาแน่น (FileCreate/FileDelete telemetry) ----------
# ransomware จริงจะแตะไฟล์จำนวนมากในเวลาสั้น - จำลอง pattern นั้นด้วย file op ปกติ
Write-Host "[ransom] mass file operations"
for ($round = 1; $round -le 3; $round++) {
    1..40 | ForEach-Object {
        $src = Join-Path $victim "work_${round}_$_.dat"
        "data chunk $round-$_ $(Get-Date -Format o)" | Out-File $src
    }
    Get-ChildItem $victim -Filter "work_${round}_*.dat" | ForEach-Object {
        Copy-Item $_.FullName "$($_.FullName).bak"
        Remove-Item $_.FullName -Force
    }
    Remove-Item "$victim\work_${round}_*.bak" -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# ---------- Stage 6: ransom note ----------
$note = @"
!!! LAB SIMULATION - NOT REAL RANSOMWARE !!!
Generated by an academic thesis experiment for dataset creation.
No real files were harmed. All activity confined to C:\lab_sandbox.
"@
$note | Out-File "$victim\READ_ME_RANSOM.txt" -Encoding utf8

# ---------- Stage 7: ลบร่องรอย ----------
Write-Host "[ransom] indicator removal"
Atomic "T1070.004" "4,5,6,7,9,10,11"  # Indicator Removal - File Deletion

# ---------- ตัวเลือก: Inhibit System Recovery (T1490) ----------
# ART มี Windows test สำหรับ T1490 (vssadmin delete shadows / bcdedit)
# เป็นพฤติกรรม hallmark ของ ransomware จริง และมีค่าต่อ detection มาก
#
# แต่มันลบ shadow copy ของ VM จริง - เปิดใช้ได้เฉพาะเมื่อ:
#   1. มั่นใจว่า revert snapshot ทุกรอบ (orchestrator ทำให้แล้ว)
#   2. ไม่มีวันรันสคริปต์นี้บนเครื่องที่ไม่มี snapshot
#   3. บันทึกไว้ในธีสิสว่าเปิดใช้
#
# ตรวจเลข test ก่อนด้วย: Invoke-AtomicTest T1490 -ShowDetailsBrief
# Atomic "T1490" "<เลข test>"

# ---------- Cleanup ----------
Write-Host "[ransom] cleanup"
Atomic-Cleanup "T1486" "5,8,10"
Atomic-Cleanup "T1074.001" "1,3"

Done-Banner "ransomware_win"